### ISSUE TITLE
How to show the videos?

### ISSUE THREAD

**Issue by Fastidious** [stevemk14ebr/YTCH#2]
Something is missing, right? I get the adjusting screen (colours) screen, but no videos. Is there something that needs to be done at YouTube (API access?) to make it work?

**Comment by stevemk14ebr** [comment]
The list.json is probably out of date, go to the original website and download the list from the network tab using the developer tools

Eventually I'll change how the original works so the list is calculated on the front end and doesn't need to download which videos to play on each channel
